### ISSUE TITLE
infinite loading screen and disconnected from RGL

### ISSUE THREAD

**Issue by jishank3489** [kagikn/ExeIntegrityBypassAgainstRGL#2]
![image](https://github.com/kagikn/ExeIntegrityBypassAgainstRGL/assets/80577806/a805d728-ca4c-41d4-9539-61b974ff9f34)

**Comment by kagikn** [comment]
Definitely insufficient info to confirm this mod indeed has the issues related to this issue. Provide info as much as you can. It would be great if you could provide how to reproduce.
