### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Michael21107** [kagikn/ExeIntegrityBypassAgainstRGL#3]
does this simply allow use of older gtav versions and use of SHV (and therefor SHVDN) without the need to backup any files file and revert them later?

**Comment by kagikn** [comment]
this doesn't, only avoids failing to check the old sign (see #1 for details), and you still need older files to launch the game in a older version between b2060 and b2802!

**Comment by kagikn** [comment]
Kind of, you would have to update Rockstar Games Launcher to launch the game, but you can stay on a version between b2060 and b2802 with relevant older exe and other game file resources (at least `update.rpf`s).

**Comment by Michael21107** [comment]
what about the 3028 (or smthg like that)?

**Comment by kagikn** [comment]
you don't need to install this mod when you use the build 2824 or newer, because no mandatory checks will fail (see #1 for details)

**Comment by Michael21107** [comment]
so i have to update the game and only after the version gets verified i can revert back correct?

**Comment by Michael21107** [comment]
gotcha, thanks
