### ISSUE TITLE
Chance of allowing this to work in reverse?

### ISSUE THREAD

**Issue by nomakewan** [kagikn/ExeIntegrityBypassAgainstRGL#5]
So with the release of 1.0.3179.0, now users on non-Windows-10 builds have no viable bypass strategy for the version check. This is because we are stuck on an older version of RGL, and while this bypass works fine to allow that version to run 3095 and older, the check against 3179 (a newer EXE than the RGL version) fails.

Any chance there's a way to allow this to make newer executables pass their check with older versions of RGL?

**Comment by kagikn** [comment]
Too difficult for me to implement stuff in reverse. Better to use Windows versions supported by Microsoft as long as Rockstar supports the game for supported Windows versions.

I didn't realize this when I created this plugin, but alloc8or told us what this plugin does is basically ignoring what the social club issuer (see #1 for details) is. I believe making RGL ignore the game version will cost me way more time to implement than making GTA5.exe ignore the social club issuer (in between v1.0.2060.0 and v1.0.2802.0) by patching single instruction. Maybe I would end up wasting a lot of time if I do that.
